---
title: "Sensitivity to tau"
format: html
---

```{r}
#| label: init
#| message: false
library(tidyverse)
library(targets)
tar_source()
tar_load_everything()
```

In the current draft (May 12th), Eda modelled the data by ignoring the first chunk when calculating the likelihood.

Here are the predictions using the parameters reported in the paper:

```{r}
#| label: predictions
paper_params <- structure(
  c(prop = 0.21, prop_ltm = 0.55, tau = 0.14, gain = 25, rate = 0.02),
  class = "serial_recall_pars"
)

exp1_data_agg$pred <- predict(paper_params, data = exp1_data_agg, group_by = c("chunk", "gap"))

exp1_data_agg |>
  ggplot(aes(x = gap, y = p_correct, color = chunk)) +
  geom_point() +
  geom_line() +
  geom_line(aes(y = pred), linetype = "dashed") +
  facet_wrap(~itemtype)
```

Strangely, there is a mismatch between these results and what is reported in the paper.

This is because the predictions are extremely sensitive to small changes in tau:

```{r}
params <- list(paper_params, paper_params, paper_params)
params[[2]][["tau"]] <- 0.15
params[[3]][["tau"]] <- 0.13


overall_deviance(params[[1]], exp1_data_agg, by = c("chunk", "gap"), exclude_sp1 = TRUE)
overall_deviance(params[[2]], exp1_data_agg, by = c("chunk", "gap"), exclude_sp1 = TRUE)
overall_deviance(params[[3]], exp1_data_agg, by = c("chunk", "gap"), exclude_sp1 = TRUE)

exp1_data_agg$pred2 <- predict(params[[2]], data = exp1_data_agg, group_by = c("chunk", "gap"))
exp1_data_agg$pred3 <- predict(params[[3]], data = exp1_data_agg, group_by = c("chunk", "gap"))

exp1_data_agg |>
  pivot_longer(cols = starts_with("pred"), names_to = "tau", values_to = "pred") |>
  mutate(tau = case_when(
    tau == "pred" ~ "0.14",
    tau == "pred2" ~ "0.15",
    tau == "pred3" ~ "0.13"
  )) |>
  ggplot(aes(x = gap, y = p_correct, color = chunk)) +
  geom_point() +
  geom_line() +
  geom_line(aes(y = pred), linetype = "dashed") +
  facet_grid(tau ~ itemtype)
```